social:
  twitter: https://x.com/_italai
  linkedin: https://www.linkedin.com/company/italai/
markdown: kramdown
kramdown:
  toc_levels: 2..5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
baseurl: "/ItalAI"   # <-- your repo name
url: "https://russellshyvers.github.io"
